name: days_of_week
base_vocab_size: ???
bos_token: ???
eos_token: null
vocab_size: ???
instance:
  _target_: simplexity.generative_processes.builder.build_hidden_markov_model
  process_name: days_of_week
