name: even_ones
base_vocab_size: ???
bos_token: ???
eos_token: null
vocab_size: ???
instance:
  _target_: simplexity.generative_processes.builder.build_hidden_markov_model
  process_name: even_ones
  p: 0.5
