name: fanizza
base_vocab_size: ???
bos_token: ???
eos_token: null
vocab_size: ???
instance:
  _target_: simplexity.generative_processes.builder.build_generalized_hidden_markov_model
  process_name: fanizza
  alpha: 2000.0
  lamb: 0.49
