name: post_quantum
base_vocab_size: ???
bos_token: ???
eos_token: null
vocab_size: ???
instance:
  _target_: simplexity.generative_processes.builder.build_generalized_hidden_markov_model
  process_name: post_quantum
  log_alpha: 1
  beta: 0.5
