name: rrxor
base_vocab_size: ???
bos_token: ???
eos_token: null
vocab_size: ???
instance:
  _target_: simplexity.generative_processes.builder.build_hidden_markov_model
  process_name: rrxor
  pR1: 0.5
  pR2: 0.5
