name: tom_quantum
base_vocab_size: ???
bos_token: ???
eos_token: null
vocab_size: ???
instance:
  _target_: simplexity.generative_processes.builder.build_generalized_hidden_markov_model
  process_name: tom_quantum
  alpha: 1.0
  beta: 1.0
