name: zero_one_random
base_vocab_size: ???
bos_token: ???
eos_token: null
vocab_size: ???
instance:
  _target_: simplexity.generative_processes.builder.build_hidden_markov_model
  process_name: zero_one_random
  p: 0.5
