name: hooked_transformer
instance:
  _target_: transformer_lens.HookedTransformer
  cfg:
    _target_: transformer_lens.HookedTransformerConfig
    d_model: 64
    d_head: 32
    n_heads: 4
    n_layers: 4
    n_ctx: ???
    d_mlp: 256
    d_vocab: ???
    act_fn: "relu"
    normalization_type: "LN"
    device: "auto"
    seed: ${seed}

load_checkpoint_step: null
