name: mlflow_persister

instance:
  _target_: simplexity.persistence.mlflow_persister.MLFlowPersister
  experiment_name:
  run_name:
  tracking_uri:
  registry_uri:
  artifact_path: models
  registered_model_name: demo_model
  downgrade_unity_catalog: true
